### ISSUE TITLE
bump to 21w40a

### ISSUE THREAD

**Issue by PortableGames** [NikitaCartes/EasyAuth#16]
add support for latest snapshots eg 21w38a 39a

**Comment by NikitaCartes** [comment]
There is no server-side translation since it doesn't update to snapshots.

And i'm not even sure that you can create 21w39a fabric server (but it should work with 21w38a and older, there is almost none changes)

[easyauth-mc21w39a-2.0.2.zip](https://github.com/NikitaCartes/EasyAuth/files/7272138/easyauth-mc21w39a-2.0.2.zip)

**Comment by NikitaCartes** [comment]
@PortableGames 

There is no server-side translation since it doesn't update to snapshots.

And i'm not even sure that you can create 21w39a fabric server (but it should work with 21w38a and older, there is almost none changes)

[easyauth-mc21w39a-2.0.2.zip](https://github.com/NikitaCartes/EasyAuth/files/7272138/easyauth-mc21w39a-2.0.2.zip)

**Comment by PortableGames** [comment]
@NikitaCartes 
yes you are right I am currently running a server on 21w38a with 21w39a client connection support .. will this version you sent work on 21w38a ?

**Comment by NikitaCartes** [comment]
It should work starting with 21w37a but i didn't test it except 21w39a

**Comment by PortableGames** [comment]
@NikitaCartes 
mod is working but I have some problems can you give me a moment on discord?

with onlinemod:true the warez can't connect .. and with false. it continuously asks for /register again every time I reconnect .. where could be the problem?


PortableGames#3564

**Comment by NikitaCartes** [comment]
Reopen in case of mod will be broken at new snapshot
