### ISSUE TITLE
[BUG] Windows defender false(?) positive issue

### ISSUE THREAD

**Issue by kryakvanya** [NikitaCartes/EasyAuth#168]
**Versions**
* EasyAuth 3.0.19
* Fabric API 0.92.2

**Describe the bug**
Windows defender marks mod's .jar file as a virus (Trojan:AndroidOS/ZkarletFlash)

**To Reproduce**
1. Launch minecraft
2. See "Incompatible mods found!" screen
3. Read
FileNotFoundException: *path to mods folder*\easyauth-mc1.20-3.0.19. jar (Операция не
была успешно завершена, так как файл содержит вирус или потенциально нежелательную программу)

**Expected behavior**
minecraft launches and works fine like it did yesterday and the day before

**Comment by NikitaCartes** [comment]
It's a false positive, and the reason (I think) some antiviruses trigger on this file is because I tried to recompress included libraries to make the JAR smaller.

You can download 3.0.19 from GitHub, and it will not trigger antiviruses:
https://github.com/NikitaCartes/EasyAuth/releases/tag/3.0.19

You can also compare versions from Modrinth/CurseForge and GitHub and see that their content is identical
