### ISSUE TITLE
[BUG] People can use any command without login in 1.19

### ISSUE THREAD

**Issue by JoinChang** [NikitaCartes/EasyAuth#52]
**Versions**
* EasyAuth 3.0.0
* Fabric API 0.55.3

**Describe the bug**
People can use any command without login in 1.19.

**To Reproduce**
1. Connect to the server
2. Type any other command without `/login`, such as `/op`

**Expected behavior**
Return unauthorized.

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/35451392/175476712-0c0d4bea-659b-48bb-ae1d-0337d39db771.png)
![image](https://user-images.githubusercontent.com/35451392/175478225-d0b0f785-5058-4be5-b948-228de149ffdb.png)

Config:
![image](https://user-images.githubusercontent.com/35451392/175477345-80996049-ecfb-4a30-91fb-785257e75ea7.png)

**Comment by were491** [comment]
```
@Mixin(CommandManager.class)
public class CommandManagerMixin {
    @Inject(method = "execute(Lnet/minecraft/server/command/ServerCommandSource;Ljava/lang/String;)I", at = @At("HEAD"), cancellable = true)
    private void checkCanUseCommands(ServerCommandSource source, String command, CallbackInfoReturnable<Integer> cir) {
        if (command.startsWith("login") || command.startsWith("register") || command.startsWith("l")) {
            return;
        }

        ServerPlayerEntity player = source.getPlayer();
        if (player == null) {
            // If the source is not a player.
            return;
        }

        if (!((PlayerAuth) player).isAuthenticated()) {
            player.sendMessage(Text.literal("Not authenticated blah blah blah").formatted(Formatting.RED), false);
            cir.setReturnValue(1);
        }
    }
}
```

@NikitaCartes you commit this code or whatever i'm sleepyyy goodnight  
sorry if it's poorly written but i'm like 2 iq right now because i can't sleeep and yeah  
oh and delete the part that used to filter this from the AuthEventHandler thingy  
it's not necessary anymore

it's probably because the chat filter changed how commands are handled in 1.19: before, they'd be handled as regular chat messages before being passed to the command manager (for some really dumb reason idk why), now they're handled separately because y'know chat filtering and all... shouldn't try and censor the command or bad things would happen

if you're wondering why i keep slightly changing this message it's because idk  
idk why

**Comment by NikitaCartes** [comment]
You can download update [here](https://github.com/NikitaCartes/EasyAuth/releases/tag/3.0.0-7)
